### ISSUE TITLE
BadParcelableException while trying to implement ViewPagerTabScrollViewActivity

### ISSUE THREAD

**Issue by youfacepalm** [ksoichiro/Android-ObservableScrollView#139]
My fragments in the view pager have a custom map view which intercepts ACTION_DOWN and ACTION_UP events so that the scrollview does not take priority when user interacts with it. I followed the code sample to implement the functionality and it worked. but after rotating the device or swiping through some pages, I get BadParcelableException. Here is the logcat output

android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.github.ksoichiro.android.observablescrollview.ObservableScrollView$SavedState
            at android.os.Parcel.readParcelableCreator(Parcel.java:2295)
            at android.os.Parcel.readParcelable(Parcel.java:2245)
            at android.os.Parcel.readValue(Parcel.java:2152)
            at android.os.Parcel.readSparseArrayInternal(Parcel.java:2546)
            at android.os.Parcel.readSparseArray(Parcel.java:1874)
            at android.os.Parcel.readValue(Parcel.java:2209)
            at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
            at android.os.BaseBundle.unparcel(BaseBundle.java:221)
            at android.os.Bundle.getBundle(Bundle.java:733)
            at com.google.android.gms.maps.internal.cv.a(SourceFile:74)
            at com.google.maps.api.android.lib6.d.fk.a(Unknown Source)
            at com.google.maps.api.android.lib6.d.ap.a(Unknown Source)
            at com.google.android.gms.maps.internal.aa.onTransact(SourceFile:66)
            at android.os.Binder.transact(Binder.java:380)
            at com.google.android.gms.maps.internal.IMapViewDelegate$zza$zza.onCreate(Unknown Source)
            at com.google.android.gms.maps.MapView$zza.onCreate(Unknown Source)
            at com.google.android.gms.dynamic.zza$3.zzb(Unknown Source)
            at com.google.android.gms.dynamic.zza$1.zza(Unknown Source)
            at com.google.android.gms.maps.MapView$zzb.zzqs(Unknown Source)
            at com.google.android.gms.maps.MapView$zzb.zza(Unknown Source)
            at com.google.android.gms.dynamic.zza.zza(Unknown Source)
            at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
            at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
            at lk.foodie.foodielogistics.UndertakenOrderDetailsFragment.onCreateView(UndertakenOrderDetailsFragment.java:215)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
            at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:490)
            at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:163)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:1072)
            at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:554)
            at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:513)
            at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:494)
            at lk.foodie.foodielogistics.views.SlidingTabLayout$TabClickListener.onClick(SlidingTabLayout.java:365)
            at android.view.View.performClick(View.java:4781)
            at android.view.View$PerformClick.run(View.java:19873)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

UndertakenOrderDetailsFragment.java:215 is CustomMapView.onCreateView(savedInstanceState); Any help would be appreciated. Thanks for the awesome library!

**Comment by youfacepalm** [comment]
Able to workaround the problem with the suggestion provided here
https://code.google.com/p/gmaps-api-issues/issues/detail?id=6237#c9
