### ISSUE TITLE
Getting NullPointerException on CacheFragmentStatePagerAdapter's restoreState when using nested fragments. 

### ISSUE THREAD

**Issue by rakeeb11** [ksoichiro/Android-ObservableScrollView#160]
The setup for my current implementation looks like this: 
* Activity
  * MainFragment
     * PagerFragment (with view pager)
        * ContentFragment 

The error occurred when I was reloading fragments from my activity and did a ```setRestoreInstance(true)``` on the MainFragment. When the fragment is recreated that is when this following error occurs from the CacheFragmentStatePagerAdapter

```java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2470)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4059)
            at android.app.ActivityThread.-wrap15(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5401)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:725)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
            at android.support.v4.app.FragmentManagerImpl.getFragment(FragmentManager.java:587)
            at com.github.ksoichiro.android.observablescrollview.CacheFragmentStatePagerAdapter.restoreState(CacheFragmentStatePagerAdapter.java:75)
            at android.support.v4.view.ViewPager.onRestoreInstanceState(ViewPager.java:1318)
            at android.view.View.dispatchRestoreInstanceState(View.java:14669)```

**Comment by macmos** [comment]
I am writing a similar problem.

My current implementation is:

Activity
    PagerFragment (with View Pager)
        Content Fragment.

Kindly helo

**Comment by eneim** [comment]
I personally don't think the recent implementation of CacheFragmentStatePagerAdapter is a good practice. @ksoichiro

**Comment by Foivos-Stamopoulos** [comment]
Great library and thank you! Unfortunatelly I am facing the same error. Do you have anything newer about this?
