### ISSUE TITLE
Crash while scrolling in RecyclerView after onItemChanged(pos) has been called

### ISSUE THREAD

**Issue by tylerjroach** [ksoichiro/Android-ObservableScrollView#182]
This crash occurs after calling recyclerAdapter.notifyItemChanged(pos), then scrolling down to the bottom of the recyclerView.
    
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getHeight()' on a null object reference
            at com.github.ksoichiro.android.observablescrollview.ObservableRecyclerView.onScrollChanged(ObservableRecyclerView.java:102)
            at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:3622)
            at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:3806)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:549)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5430)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)

**Comment by ksoichiro** [comment]
@tylerjroach What version of this library do you use?
In the latest master branch, there's no `getHeight()` in `ObservableRecyclerView.java:102`.

If you are using old one, please try the latest SNAPSHOT to see if it still has the issue.
You can try `1.6.0-SNAPSHOT` with this:

```gradle
repositories {
    mavenCentral()
    maven {
        url uri('https://oss.sonatype.org/content/repositories/snapshots/')
    }
}

dependencies {
    compile "com.github.ksoichiro:android-observablescrollview:1.6.0-SNAPSHOT"
}
```

**Comment by tylerjroach** [comment]
@ksoichiro Thanks for the response! The snapshot works without crashing. I was using 1.5.2, but I notice the 1.6.0 snapshot includes these two commits that addressed NPEs: 

b56552270ead6ccf815abbff55e94784cd172515
db593e383c2ba90d75c009ca54cf6417c7fecedf
