### ISSUE TITLE
Null Pointer exception at ObservableRecyclerView.onScrollChanged(ObservableRecyclerView.java:102) 'int android.view.View.getHeight()'

### ISSUE THREAD

**Issue by nikhilverma1395** [ksoichiro/Android-ObservableScrollView#221]
FATAL EXCEPTION: main
                                                   Process: razor.nikhil, PID: 20454
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getHeight()' on a null object reference
                                                       at com.github.ksoichiro.android.observablescrollview.ObservableRecyclerView.onScrollChanged(ObservableRecyclerView.java:102)
                                                       at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:3797)
                                                       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2958)
                                                       at android.support.v7.widget.RecyclerView.resumeRequestLayout(RecyclerView.java:1599)
                                                       at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:277)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:549)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5290)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by ksoichiro** [comment]
Thank you for your report and sorry for my late reply.
It seems you're using v1.5.2, but this bug is fixed in b565522 and released as v1.6.0.
Please update the library to v1.6.0.
If you still face this issue in v1.6.0, please reopen this issue.
