### ISSUE TITLE
Issue with the RecyclerView state on Android 5.0.2

### ISSUE THREAD

**Issue by scan** [ksoichiro/Android-ObservableScrollView#27]
I'm using `ObservableRecyclerView` and it works fine on Android <5. But when I run the same code on Lollipop, I get an exception. The RecyclerView has elements, a click on them starts another activity. When I return from that one, the app crashes with the following exception:

```
Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: android.support.v7.widget.RecyclerView$SavedState
            at android.os.Parcel.readParcelableCreator(Parcel.java:2289)
            at android.os.Parcel.readParcelable(Parcel.java:2239)
            at android.view.AbsSavedState.<init>(AbsSavedState.java:57)
            at android.view.View$BaseSavedState.<init>(View.java:20038)
            at com.github.ksoichiro.android.observablescrollview.ObservableRecyclerView$SavedState.<init>(ObservableRecyclerView.java:265)
            at com.github.ksoichiro.android.observablescrollview.ObservableRecyclerView$SavedState.<init>(ObservableRecyclerView.java:252)
            at com.github.ksoichiro.android.observablescrollview.ObservableRecyclerView$SavedState$1.createFromParcel(ObservableRecyclerView.java:304)
            at com.github.ksoichiro.android.observablescrollview.ObservableRecyclerView$SavedState$1.createFromParcel(ObservableRecyclerView.java:301)
            at android.os.Parcel.readParcelable(Parcel.java:2246)
            at android.os.Parcel.readValue(Parcel.java:2146)
            at android.os.Parcel.readSparseArrayInternal(Parcel.java:2540)
            at android.os.Parcel.readSparseArray(Parcel.java:1868)
            at android.os.Parcel.readValue(Parcel.java:2203)
            at android.os.Parcel.readArrayMapInternal(Parcel.java:2479)
            at android.os.BaseBundle.unparcel(BaseBundle.java:221)
            at android.os.Bundle.getSparseParcelableArray(Bundle.java:871)
            at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1979)
            at android.app.Activity.onRestoreInstanceState(Activity.java:1022)
            at android.app.Activity.performRestoreInstanceState(Activity.java:977)
            at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1161)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2271)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

It looks like on Lollipop, the `android.support.v7.widget.RecyclerView` is not used by the app since it has the native one available. But the `ObservableRecyclerView` references that one, leading to the crash.

**Comment by ppamorim** [comment]
+1 Still happens this problem.

**Comment by oshurmamadov** [comment]
++ Still happens

**Comment by lehno** [comment]
+1 Still happens this problem.

**Comment by onexuan** [comment]
this issue is support lib bug, https://code.google.com/p/android/issues/detail?id=196430

**Comment by icodeyou** [comment]
+1
