### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.BaseBundle.getInt(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by arundwi09** [ksoichiro/Android-ObservableScrollView#289]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.BaseBundle.getInt(java.lang.String)' on a null object reference
       at com.github.ksoichiro.android.observablescrollview.a.restoreState(SourceFile:71)
       at android.support.v4.view.ViewPager.setAdapter(SourceFile:528)
       ---------
       at android.os.AsyncTask.finish(AsyncTask.java:660)
       at android.os.AsyncTask.-wrap1(AsyncTask.java)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6162)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by arundwi09** [comment]
can't we add null check in restoreState method, like
```
if (state != null) {
    //TODO
} else {
    super.restoreState(state, loader);
}
```
