### ISSUE TITLE
android.view.AbsSavedState$1 cannot be cast to com.github.ksoichiro.android.observablescrollview.ObservableScrollView$SavedState

### ISSUE THREAD

**Issue by DavePilks** [ksoichiro/Android-ObservableScrollView#85]
I keep getting this when I use the ObservableListView and rotate

Caused by: java.lang.ClassCastException: android.view.AbsSavedState$1 cannot be cast to com.github.ksoichiro.android.observablescrollview.ObservableScrollView$SavedState
            at com.github.ksoichiro.android.observablescrollview.ObservableScrollView.onRestoreInstanceState(ObservableScrollView.java:60)
            at android.view.View.dispatchRestoreInstanceState(View.java:13188)
            at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2850)
            at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2856)
            at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2856)
            at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2856)
            at android.view.View.restoreHierarchyState(View.java:13166)
            at android.support.v4.app.Fragment.restoreViewState(Fragment.java:465)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:969)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
            at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1917)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:544)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1188)
            at android.app.Activity.performStart(Activity.java:5382)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2266)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3877)
            at android.app.ActivityThread.access$800(ActivityThread.java:159)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1322)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:176)
            at android.app.ActivityThread.main(ActivityThread.java:5419)
            at java.lang.reflect.Method.invokeNative(Native Method)

**Comment by lucasvdev** [comment]
Hi,

Was it solved ?
